# Nombre de la aplicación
spring.application.name=invitarlyweb

# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/invitarly?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Logging para ver las consultas SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

mercadopago.access-token=APP_USR-7830270374744728-012709-3c4cdeb498ae9d982acc8b7ffa5fa231-2228858887
MERCADOPAGO_PUBLIC_KEY=APP_USR-ee8e378c-5513-40da-8552-8ca823eef6ab

# Configuración de correo con Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=invitarly@gmail.com
spring.mail.password=vxkt ypvy jgtz rfxb
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.default-encoding=UTF-8

invitarly.notificacion.email=invitarly@gmail.com

logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.mail.javamail=DEBUG

# Clave JWT en base64 (ejemplo)
jwt.secret=Zm9vYmFyYmF6LWVuY3J5cHRlZC1jbGF2ZQ==

# Tiempo de expiración en milisegundos (opcional)
jwt.expirationMs=3600000